name: core
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  dio: ^5.3.2
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
